### ISSUE TITLE
CO EL7500 BC is not being calculated correctly for regulated/unregulated section.

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#487] opened 2016-05-20 12:57 UTC

**Comment by HansVraga** [comment] 2016-10-07 20:09
Jeremy thinks that: Currently the issue is that the Regulated grabs the Unregulated value.

**Comment by marsmith** [comment] 2016-10-07 20:21
related to #463

**Comment by marsmith** [comment] 2016-10-12 14:03
One issue is list of precomputed BCs is not the same as what is showing as available from services

```
"percentarearegulated": 88.700699935105547,
  "parameters": [
    {
      "operation": "Sum",
      "code": "DRNAREA",
      "value": 334.05233004
    },
    {
      "operation": "WeightedAverage",
      "operationField": "DRNAREA",
      "code": "ELEV",
      "value": 10967.28797381402
    },
    {
      "operation": "WeightedAverage",
      "operationField": "DRNAREA",
      "code": "I6H100Y",
      "value": 2.2772934480411249
    },
    {
      "operation": "WeightedAverage",
      "operationField": "DRNAREA",
      "code": "PRECIP",
      "value": 27.09341991767122
    },
    {
      "operation": "WeightedAverage",
      "operationField": "DRNAREA",
      "code": "EL7500",
      "value": 1.0
    },
    {
      "operation": "WeightedAverage",
      "operationField": "DRNAREA",
      "code": "BSLDEM10M",
      "value": 33.627760264577688
    }
  ]
```

Services:
http://ssdev.cr.usgs.gov/streamstatsservices/parameters.json?rcode=CO

**Comment by marsmith** [comment] 2016-10-12 14:19
Second issue is with display of EL7500

params back from regular compute params call:

```
{
  "parameters": [
    {
      "name": "DRNAREA",
      "description": "Area that drains to a point on a stream",
      "code": "DRNAREA",
      "unit": "square miles",
      "value": 391
    },
    {
      "name": "PRECIP",
      "description": "Mean Annual Precipitation",
      "code": "PRECIP",
      "unit": "inches",
      "value": 26.68
    },
    {
      "name": "I6H100Y",
      "description": "6-hour precipitation that is expected to occur on average once in 100 years",
      "code": "I6H100Y",
      "unit": "inches",
      "value": 2.26
    },
    {
      "name": "ELEV",
      "description": "Mean Basin Elevation",
      "code": "ELEV",
      "unit": "feet",
      "value": 10900
    },
    {
      "name": "BSLDEM10M",
      "description": "Mean basin slope computed from 10 m DEM",
      "code": "BSLDEM10M",
      "unit": "percent",
      "value": 33.6
    },
    {
      "name": "EL7500",
      "description": "Percent of area above 7500 ft",
      "code": "EL7500",
      "unit": "percent",
      "value": 100
    },
    {
      "name": "OUTLETELEV",
      "description": "Elevation of the stream outlet in feet above NAVD88.",
      "code": "OUTLETELEV",
      "unit": "feet",
      "value": 8565
    },
    {
      "name": "STATSCLAY",
      "description": "Percentage of clay soils from STATSGO",
      "code": "STATSCLAY",
      "unit": "percent",
      "value": 14.54
    }
  ],
  "messages": [
    "From ApFields",
    "count: 8",
    "DB definition return count: 8",
    "Start Time: Wed Oct 12 08:17:44 2016 Performing global parameters computation... Succeeded at Wed Oct 12 08:17:52 2016 (Elapsed Time: 7.23 seconds)"
  ]
}
```

params from regulated dam:

```
 "parameters": [
    {
      "operation": "Sum",
      "code": "DRNAREA",
      "value": 334.05233004
    },
    {
      "operation": "WeightedAverage",
      "operationField": "DRNAREA",
      "code": "ELEV",
      "value": 10967.28797381402
    },
    {
      "operation": "WeightedAverage",
      "operationField": "DRNAREA",
      "code": "I6H100Y",
      "value": 2.2772934480411249
    },
    {
      "operation": "WeightedAverage",
      "operationField": "DRNAREA",
      "code": "PRECIP",
      "value": 27.09341991767122
    },
    {
      "operation": "WeightedAverage",
      "operationField": "DRNAREA",
      "code": "EL7500",
      "value": 1.0
    },
    {
      "operation": "WeightedAverage",
      "operationField": "DRNAREA",
      "code": "BSLDEM10M",
      "value": 33.627760264577688
    }
  ]
```

but showing as :
![image](https://cloud.githubusercontent.com/assets/6529123/19313753/a0880508-9065-11e6-9676-d87f0f56fa85.png)

should be 100 and 100

**Comment by marsmith** [comment] 2016-10-12 15:48
fixed in services

**Closed as completed by marsmith** 2016-10-12 15:48 UTC
Labels: bug
