### ISSUE TITLE
Modal Styling 

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#943] opened 2018-09-19 15:11 UTC
Modals used for State customization tools could use some styling refreshes.
Fields tend to be wider than needed for use.
Buttons span the width of the modal - to the point where it may appear not to be a button
Warning messages can act funky if text size is set higher by user, or unique resolutions force the modal size smaller. See images below

![image](https://user-images.githubusercontent.com/12058013/45762118-e3007700-bbea-11e8-909a-5b947813ad8e.png)

![image](https://user-images.githubusercontent.com/12058013/45762291-47bbd180-bbeb-11e8-9901-8f4d13941e1e.png)

![image](https://user-images.githubusercontent.com/12058013/45762467-a719e180-bbeb-11e8-9e9e-450e4fa757ef.png)

**Comment by jknewson** [comment] 2018-11-27 17:57
duplicate of #938

**Closed as completed by jknewson** 2018-11-27 17:57 UTC
