### ISSUE TITLE
Something funky with failed basin characteristics 

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats#561] opened 2016-11-15 17:53 UTC
No errors showing up in OR during error on BC's
Should open "Show basin characteristics" with recalculate.

**Comment by marsmith** [comment] 2016-11-15 18:23
Also intermittent appearance of "calculate missing characteristics"

**Comment by marsmith** [comment] 2016-11-28 15:50
duplicate of #566 , closing

**Closed as completed by marsmith** 2016-11-28 15:50 UTC
