### ISSUE TITLE
Water-Use Download issue

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#950] opened 2018-11-02 15:01 UTC
From cooperator:
> I’m able to download the Table CSV but not the Source CSV.  The message popup asking “Do you want to save….”  doesn’t display when I click the Source CSV option.

**Comment by jknewson** [comment] 2018-11-27 16:41
I can't reproduce issue. I've tested locally as well as on test server. Closing for now

**Closed as completed by jknewson** 2018-11-27 16:41 UTC
