### ISSUE TITLE
Regulation: dealing with new BCs

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#591] opened 2016-12-07 17:34 UTC
Currently for CO (and if we end up implementing regulation in other states) if a new BC is added, it looks like it's not computed when you compute BCs (see image). In reality, we know the BC for the whole basin, but don't have the data for the regulated region. We should let the user know explicitly the new BC data is not available in some way.

If you continue to the final report, you do get to see the new BC's value for the total Basin.

*Suggestion:*
We should show a "N/A" and include a red toaster for each BC not available for the regulated region stating "[BC name] not available for regulated / unregulated breakdown"

![image](https://cloud.githubusercontent.com/assets/12058013/20978993/fb47be7c-bc78-11e6-9323-972d9f4e5183.png)

**Comment by marsmith** [comment] 2017-02-14 14:32
I'll look into if this is possible on the front end, but may need to be handled in the regulation services

**Comment by jknewson** [comment] 2017-02-14 15:49
duplicate of #590

**Closed as completed** 2017-02-16 13:40 UTC
